[tool.black]
line-length = 110
target-version = ['py38', 'py39']
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose --cov=mood --cov-report xml --cov-report term"
testpaths = ["tests"]

[tool.coverage.run]
omit = ["setup.py", "tests/*"] 
